# Generated by cucumber-sinatra. (2014-06-23 13:22:14 -0700)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', './canto.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Canto

class CantoWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  CantoWorld.new
end
