# Generated by cucumber-sinatra. (2014-06-27 15:36:37 -0700)

require 'simplecov'
require 'coveralls'

SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter[
  SimpleCov::Formatter::HTMLFormatter,
  Coveralls::SimpleCov::Formatter
]
SimpleCov.start if ENV["COVERAGE"]

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', './canto.rb')

require 'rspec'
require 'json_spec/cucumber'
require 'rack/test'

class CantoWorld
  include RSpec::Expectations
  include RSpec::Matchers
  include RSpec::Mocks
  include Rack::Test::Methods
  include JsonSpec

  def app
    Canto.new
  end

  def last_json
    page.source
  end
end

World do
  CantoWorld.new
end
